### ISSUE TITLE
Disabling the automatic SQL to JS native type conversion.

### ISSUE THREAD

**Issue by mortiy** [mariano/node-db#2]
Hi.
Here http://nodejsdb.org/ said that disabling the automatic conversion can increase speed up to 200%.
How can I disable it?

**Comment by mariano** [comment]
Set the cast option to false when creating the query:

``` javascript
this.query({ cast: false })
        .select(["id", "user", "email"])
        ....
```

Let me know how it goes

**Comment by mariano** [comment]
BTW this is documented:

http://nodejsdb.org/docs/#query_execute

**Comment by mortiy** [comment]
Thank you, missed that (that is really small line :) )

**Comment by mariano** [comment]
haha sorry. It is an option most people wouldn't use, that's why it's not that evident :)
